#pragma once

enum class GameState {
    TITLE_SCREEN,
    MAIN_MENU,
    LESSONS_TITLE,
    LESSONS_HTP,
    LESSONS_SELECTION,
    LESSONS_MODE,
    LESSONS_RESULTS,
    ARCADE_TITLE,
    ARCADE_HTP,
    ARCADE_MODE,
    ARCADE_RESULTS,
    BONUS_TITLE,
    BONUS_STAGE,
    BONUS_RESULTS,
    SPEED_MODE,
    RIP_MODE,
    GAME_OVER,
    RECORDS,
    WPM_TEST,
    WPM_RESULTS,
    PAUSE
};