#pragma once

enum class GameState {
    TITLE_SCREEN,
    MAIN_MENU,
    ARCADE_TITLE,
    ARCADE_HTP,
    ARCADE_MODE,
    ARCADE_RESULTS,
    BONUS_TITLE,
    BONUS_STAGE,
    BONUS_RESULTS,
    SPEED_MODE,
    LESSON_MODE,
    RIP_MODE,
    GAME_OVER,
    PAUSE
};